export const genreMap: Record<string, string> = {
    'Fiction': 'Fiction',
    'Nonfiction': 'Nonfiction',
    'Science': 'Science',
    'Business': 'Business',
    'Graphic Novels': 'Comics & Graphic Novels',
    'Children': 'Juvenile Fiction',
    'Romance': 'Romance',
    'Mystery': 'Mystery',
    'History': 'History',
    'Poetry': 'Poetry',
    'Biography': 'Biography & Autobiography',
    'Fantasy': 'Fantasy',
    'Self-Help': 'Self-Help',
    'Technology': 'Technology',
    'Health': 'Health & Fitness',
    'Education': 'Education',
};
